language: ruby

cache: bundler

sudo: false

rvm:
  - 2.2.3

gemfile:
  - Gemfile

services:
  - redis-server

before_script:
  - cp config/database.yml.copyme config/database.yml
  - bundle exec rake db:migrate
